services:
  newapi:
    image: calciumion/new-api:latest
    container_name: new-api
    restart: always
    ports:
      - "3002:3000"
    volumes:
      - ./data:/data
    environment:
      - TZ=Asia/Shanghai
