services:
  blog:
    image: nginx:alpine
    container_name: blog
    restart: always
    ports:
      - "8092:80"
    volumes:
      - ./landing/index.html:/usr/share/nginx/html/index.html:ro
      - ./landing/robots.txt:/usr/share/nginx/html/robots.txt:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
